# Generated by Django 3.2.7 on 2021-11-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('is_active', models.BooleanField(default=True)),
                ('until_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escreva o nome da matéria', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('resposta_texto', models.CharField(max_length=200)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicios')),
            ],
        ),
        migrations.AddField(
            model_name='exercicios',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercicios.materia'),
        ),
        migrations.AddField(
            model_name='exercicios',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExercicioInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico desse exercício', primary_key=True, serialize=False)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('acertou', models.BooleanField(null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Acerto'), ('e', 'Erro'), ('n', 'Não Respondido'), ('t', 'Atrasado')], default='n', help_text='Status do exercício', max_length=1)),
                ('alternativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exercicios.respostas')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exercicios.exercicios')),
            ],
            options={
                'ordering': ['until_date'],
            },
        ),
    ]
